# This file shouldn't really be committed to git, but it's here for demo purposes
#
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  # echo -n "i am a secret" | base64
  MY_SUPER_SECRET: c2VjcmV0
